/**
 * srd-data.js — SRD 5.1 reference data
 * Content licensed under Creative Commons Attribution 4.0 International (CC BY 4.0)
 * Source: Systems Reference Document 5.1 by Wizards of the Coast
 */

/* ============================================================
   SUBCLASSES — SRD 5.1 core classes
   ============================================================ */
const SRD_SUBCLASSES = {
  Barbarian: ['Path of the Berserker', 'Path of the Totem Warrior'],
  Bard:      ['College of Lore', 'College of Valor'],
  Cleric:    ['Knowledge Domain', 'Life Domain', 'Light Domain', 'Nature Domain',
               'Tempest Domain', 'Trickery Domain', 'War Domain'],
  Druid:     ['Circle of the Land', 'Circle of the Moon'],
  Fighter:   ['Battle Master', 'Champion', 'Eldritch Knight'],
  Monk:      ['Way of the Four Elements', 'Way of the Open Hand', 'Way of Shadow'],
  Paladin:   ['Oath of Devotion', 'Oath of the Ancients', 'Oath of Vengeance'],
  Ranger:    ['Beast Master', 'Hunter'],
  Rogue:     ['Arcane Trickster', 'Assassin', 'Thief'],
  Sorcerer:  ['Draconic Bloodline', 'Wild Magic'],
  Warlock:   ['The Archfey', 'The Fiend', 'The Great Old One'],
  Wizard:    ['School of Abjuration', 'School of Conjuration', 'School of Divination',
               'School of Enchantment', 'School of Evocation', 'School of Illusion',
               'School of Necromancy', 'School of Transmutation'],
};

/* ============================================================
   SPELLS — SRD 5.1
   Fields: n=name, l=level (0=cantrip), s=school, ct=castTime,
           r=range, d=duration, c=concentration, ri=ritual, co=components
   ============================================================ */
const SRD_SPELLS = [
  // ── Cantrips ──────────────────────────────────────────────
  { n:'Acid Splash',         l:0, s:'Conjuration',   ct:'1 Action',       r:'60 ft.',                    d:'Instantaneous',          c:false, ri:false, co:'VS'  },
  { n:'Blade Ward',          l:0, s:'Abjuration',    ct:'1 Action',       r:'Self',                      d:'1 round',                c:false, ri:false, co:'VS'  },
  { n:'Chill Touch',         l:0, s:'Necromancy',    ct:'1 Action',       r:'120 ft.',                   d:'1 round',                c:false, ri:false, co:'VS'  },
  { n:'Dancing Lights',      l:0, s:'Evocation',     ct:'1 Action',       r:'120 ft.',                   d:'Conc., up to 1 min.',    c:true,  ri:false, co:'VSM' },
  { n:'Druidcraft',          l:0, s:'Transmutation', ct:'1 Action',       r:'30 ft.',                    d:'Instantaneous',          c:false, ri:false, co:'VS'  },
  { n:'Eldritch Blast',      l:0, s:'Evocation',     ct:'1 Action',       r:'120 ft.',                   d:'Instantaneous',          c:false, ri:false, co:'VS'  },
  { n:'Fire Bolt',           l:0, s:'Evocation',     ct:'1 Action',       r:'120 ft.',                   d:'Instantaneous',          c:false, ri:false, co:'VS'  },
  { n:'Friends',             l:0, s:'Enchantment',   ct:'1 Action',       r:'Self',                      d:'Conc., up to 1 min.',    c:true,  ri:false, co:'SM'  },
  { n:'Guidance',            l:0, s:'Divination',    ct:'1 Action',       r:'Touch',                     d:'Conc., up to 1 min.',    c:true,  ri:false, co:'VS'  },
  { n:'Light',               l:0, s:'Evocation',     ct:'1 Action',       r:'Touch',                     d:'1 hour',                 c:false, ri:false, co:'VM'  },
  { n:'Mage Hand',           l:0, s:'Conjuration',   ct:'1 Action',       r:'30 ft.',                    d:'1 minute',               c:false, ri:false, co:'VS'  },
  { n:'Mending',             l:0, s:'Transmutation', ct:'1 minute',       r:'Touch',                     d:'Instantaneous',          c:false, ri:false, co:'VSM' },
  { n:'Message',             l:0, s:'Transmutation', ct:'1 Action',       r:'120 ft.',                   d:'1 round',                c:false, ri:false, co:'VSM' },
  { n:'Minor Illusion',      l:0, s:'Illusion',      ct:'1 Action',       r:'30 ft.',                    d:'1 minute',               c:false, ri:false, co:'SM'  },
  { n:'Poison Spray',        l:0, s:'Conjuration',   ct:'1 Action',       r:'10 ft.',                    d:'Instantaneous',          c:false, ri:false, co:'VS'  },
  { n:'Prestidigitation',    l:0, s:'Transmutation', ct:'1 Action',       r:'10 ft.',                    d:'Up to 1 hour',           c:false, ri:false, co:'VS'  },
  { n:'Produce Flame',       l:0, s:'Conjuration',   ct:'1 Action',       r:'Self',                      d:'10 minutes',             c:false, ri:false, co:'VS'  },
  { n:'Ray of Frost',        l:0, s:'Evocation',     ct:'1 Action',       r:'60 ft.',                    d:'Instantaneous',          c:false, ri:false, co:'VS'  },
  { n:'Resistance',          l:0, s:'Abjuration',    ct:'1 Action',       r:'Touch',                     d:'Conc., up to 1 min.',    c:true,  ri:false, co:'VSM' },
  { n:'Sacred Flame',        l:0, s:'Evocation',     ct:'1 Action',       r:'60 ft.',                    d:'Instantaneous',          c:false, ri:false, co:'VS'  },
  { n:'Shillelagh',          l:0, s:'Transmutation', ct:'Bonus Action',   r:'Touch',                     d:'1 minute',               c:false, ri:false, co:'VSM' },
  { n:'Shocking Grasp',      l:0, s:'Evocation',     ct:'1 Action',       r:'Touch',                     d:'Instantaneous',          c:false, ri:false, co:'VS'  },
  { n:'Spare the Dying',     l:0, s:'Necromancy',    ct:'1 Action',       r:'Touch',                     d:'Instantaneous',          c:false, ri:false, co:'VS'  },
  { n:'Thaumaturgy',         l:0, s:'Transmutation', ct:'1 Action',       r:'30 ft.',                    d:'Up to 1 minute',         c:false, ri:false, co:'V'   },
  { n:'True Strike',         l:0, s:'Divination',    ct:'1 Action',       r:'30 ft.',                    d:'Conc., up to 1 round',   c:true,  ri:false, co:'S'   },
  { n:'Vicious Mockery',     l:0, s:'Enchantment',   ct:'1 Action',       r:'60 ft.',                    d:'Instantaneous',          c:false, ri:false, co:'V'   },

  // ── Level 1 ───────────────────────────────────────────────
  { n:'Alarm',                        l:1, s:'Abjuration',    ct:'1 minute',       r:'30 ft.',                    d:'8 hours',                c:false, ri:true,  co:'VSM' },
  { n:'Animal Friendship',            l:1, s:'Enchantment',   ct:'1 Action',       r:'30 ft.',                    d:'24 hours',               c:false, ri:false, co:'VSM' },
  { n:'Armor of Agathys',             l:1, s:'Abjuration',    ct:'1 Action',       r:'Self',                      d:'1 hour',                 c:false, ri:false, co:'VSM' },
  { n:'Arms of Hadar',                l:1, s:'Conjuration',   ct:'1 Action',       r:'Self (10-ft. radius)',       d:'Instantaneous',          c:false, ri:false, co:'VS'  },
  { n:'Bane',                         l:1, s:'Enchantment',   ct:'1 Action',       r:'30 ft.',                    d:'Conc., up to 1 min.',    c:true,  ri:false, co:'VSM' },
  { n:'Bless',                        l:1, s:'Enchantment',   ct:'1 Action',       r:'30 ft.',                    d:'Conc., up to 1 min.',    c:true,  ri:false, co:'VSM' },
  { n:'Burning Hands',                l:1, s:'Evocation',     ct:'1 Action',       r:'Self (15-ft. cone)',         d:'Instantaneous',          c:false, ri:false, co:'VS'  },
  { n:'Charm Person',                 l:1, s:'Enchantment',   ct:'1 Action',       r:'30 ft.',                    d:'1 hour',                 c:false, ri:false, co:'VS'  },
  { n:'Color Spray',                  l:1, s:'Illusion',      ct:'1 Action',       r:'Self (15-ft. cone)',         d:'1 round',                c:false, ri:false, co:'VSM' },
  { n:'Command',                      l:1, s:'Enchantment',   ct:'1 Action',       r:'60 ft.',                    d:'1 round',                c:false, ri:false, co:'V'   },
  { n:'Comprehend Languages',         l:1, s:'Divination',    ct:'1 Action',       r:'Self',                      d:'1 hour',                 c:false, ri:true,  co:'VSM' },
  { n:'Create or Destroy Water',      l:1, s:'Transmutation', ct:'1 Action',       r:'30 ft.',                    d:'Instantaneous',          c:false, ri:false, co:'VSM' },
  { n:'Cure Wounds',                  l:1, s:'Evocation',     ct:'1 Action',       r:'Touch',                     d:'Instantaneous',          c:false, ri:false, co:'VS'  },
  { n:'Detect Evil and Good',         l:1, s:'Divination',    ct:'1 Action',       r:'Self',                      d:'Conc., up to 10 min.',   c:true,  ri:false, co:'VS'  },
  { n:'Detect Magic',                 l:1, s:'Divination',    ct:'1 Action',       r:'Self',                      d:'Conc., up to 10 min.',   c:true,  ri:true,  co:'VS'  },
  { n:'Detect Poison and Disease',    l:1, s:'Divination',    ct:'1 Action',       r:'Self',                      d:'Conc., up to 10 min.',   c:true,  ri:true,  co:'VSM' },
  { n:'Disguise Self',                l:1, s:'Illusion',      ct:'1 Action',       r:'Self',                      d:'1 hour',                 c:false, ri:false, co:'VS'  },
  { n:'Divine Favor',                 l:1, s:'Evocation',     ct:'Bonus Action',   r:'Self',                      d:'Conc., up to 1 min.',    c:true,  ri:false, co:'VS'  },
  { n:'Entangle',                     l:1, s:'Conjuration',   ct:'1 Action',       r:'90 ft.',                    d:'Conc., up to 1 min.',    c:true,  ri:false, co:'VS'  },
  { n:'Expeditious Retreat',          l:1, s:'Transmutation', ct:'Bonus Action',   r:'Self',                      d:'Conc., up to 10 min.',   c:true,  ri:false, co:'VS'  },
  { n:'Faerie Fire',                  l:1, s:'Evocation',     ct:'1 Action',       r:'60 ft.',                    d:'Conc., up to 1 min.',    c:true,  ri:false, co:'V'   },
  { n:'False Life',                   l:1, s:'Necromancy',    ct:'1 Action',       r:'Self',                      d:'1 hour',                 c:false, ri:false, co:'VSM' },
  { n:'Feather Fall',                 l:1, s:'Transmutation', ct:'1 Reaction',     r:'60 ft.',                    d:'1 minute',               c:false, ri:false, co:'VM'  },
  { n:'Find Familiar',                l:1, s:'Conjuration',   ct:'1 hour',         r:'10 ft.',                    d:'Instantaneous',          c:false, ri:true,  co:'VSM' },
  { n:'Fog Cloud',                    l:1, s:'Conjuration',   ct:'1 Action',       r:'120 ft.',                   d:'Conc., up to 1 hour',    c:true,  ri:false, co:'VS'  },
  { n:'Goodberry',                    l:1, s:'Transmutation', ct:'1 Action',       r:'Touch',                     d:'Instantaneous',          c:false, ri:false, co:'VSM' },
  { n:'Grease',                       l:1, s:'Conjuration',   ct:'1 Action',       r:'60 ft.',                    d:'1 minute',               c:false, ri:false, co:'VSM' },
  { n:'Guiding Bolt',                 l:1, s:'Evocation',     ct:'1 Action',       r:'120 ft.',                   d:'1 round',                c:false, ri:false, co:'VS'  },
  { n:'Healing Word',                 l:1, s:'Evocation',     ct:'Bonus Action',   r:'60 ft.',                    d:'Instantaneous',          c:false, ri:false, co:'V'   },
  { n:'Hellish Rebuke',               l:1, s:'Evocation',     ct:'1 Reaction',     r:'60 ft.',                    d:'Instantaneous',          c:false, ri:false, co:'VS'  },
  { n:'Heroism',                      l:1, s:'Enchantment',   ct:'1 Action',       r:'Touch',                     d:'Conc., up to 1 min.',    c:true,  ri:false, co:'VS'  },
  { n:'Hex',                          l:1, s:'Enchantment',   ct:'Bonus Action',   r:'90 ft.',                    d:'Conc., up to 1 hour',    c:true,  ri:false, co:'VSM' },
  { n:"Hunter's Mark",                l:1, s:'Divination',    ct:'Bonus Action',   r:'90 ft.',                    d:'Conc., up to 1 hour',    c:true,  ri:false, co:'V'   },
  { n:'Identify',                     l:1, s:'Divination',    ct:'1 minute',       r:'Touch',                     d:'Instantaneous',          c:false, ri:true,  co:'VSM' },
  { n:'Inflict Wounds',               l:1, s:'Necromancy',    ct:'1 Action',       r:'Touch',                     d:'Instantaneous',          c:false, ri:false, co:'VS'  },
  { n:'Jump',                         l:1, s:'Transmutation', ct:'1 Action',       r:'Touch',                     d:'1 minute',               c:false, ri:false, co:'VSM' },
  { n:'Longstrider',                  l:1, s:'Transmutation', ct:'1 Action',       r:'Touch',                     d:'1 hour',                 c:false, ri:false, co:'VSM' },
  { n:'Mage Armor',                   l:1, s:'Abjuration',    ct:'1 Action',       r:'Touch',                     d:'8 hours',                c:false, ri:false, co:'VSM' },
  { n:'Magic Missile',                l:1, s:'Evocation',     ct:'1 Action',       r:'120 ft.',                   d:'Instantaneous',          c:false, ri:false, co:'VS'  },
  { n:'Protection from Evil and Good',l:1, s:'Abjuration',    ct:'1 Action',       r:'Touch',                     d:'Conc., up to 10 min.',   c:true,  ri:false, co:'VSM' },
  { n:'Purify Food and Drink',        l:1, s:'Transmutation', ct:'1 Action',       r:'10 ft.',                    d:'Instantaneous',          c:false, ri:true,  co:'VS'  },
  { n:'Ray of Sickness',              l:1, s:'Necromancy',    ct:'1 Action',       r:'60 ft.',                    d:'Instantaneous',          c:false, ri:false, co:'VS'  },
  { n:'Shield',                       l:1, s:'Abjuration',    ct:'1 Reaction',     r:'Self',                      d:'1 round',                c:false, ri:false, co:'VS'  },
  { n:'Shield of Faith',              l:1, s:'Abjuration',    ct:'Bonus Action',   r:'60 ft.',                    d:'Conc., up to 10 min.',   c:true,  ri:false, co:'VSM' },
  { n:'Silent Image',                 l:1, s:'Illusion',      ct:'1 Action',       r:'60 ft.',                    d:'Conc., up to 10 min.',   c:true,  ri:false, co:'VSM' },
  { n:'Sleep',                        l:1, s:'Enchantment',   ct:'1 Action',       r:'90 ft.',                    d:'1 minute',               c:false, ri:false, co:'VSM' },
  { n:'Speak with Animals',           l:1, s:'Divination',    ct:'1 Action',       r:'Self',                      d:'10 minutes',             c:false, ri:true,  co:'VS'  },
  { n:"Tasha's Hideous Laughter",     l:1, s:'Enchantment',   ct:'1 Action',       r:'30 ft.',                    d:'Conc., up to 1 min.',    c:true,  ri:false, co:'VSM' },
  { n:'Thunderwave',                  l:1, s:'Evocation',     ct:'1 Action',       r:'Self (15-ft. cube)',         d:'Instantaneous',          c:false, ri:false, co:'VS'  },
  { n:'Unseen Servant',               l:1, s:'Conjuration',   ct:'1 Action',       r:'60 ft.',                    d:'1 hour',                 c:false, ri:true,  co:'VSM' },
  { n:'Witch Bolt',                   l:1, s:'Evocation',     ct:'1 Action',       r:'30 ft.',                    d:'Conc., up to 1 min.',    c:true,  ri:false, co:'VSM' },

  // ── Level 2 ───────────────────────────────────────────────
  { n:'Aid',                    l:2, s:'Abjuration',    ct:'1 Action',       r:'30 ft.',              d:'8 hours',                c:false, ri:false, co:'VSM' },
  { n:'Alter Self',             l:2, s:'Transmutation', ct:'1 Action',       r:'Self',                d:'Conc., up to 1 hour',    c:true,  ri:false, co:'VS'  },
  { n:'Animal Messenger',       l:2, s:'Enchantment',   ct:'1 Action',       r:'30 ft.',              d:'24 hours',               c:false, ri:true,  co:'VSM' },
  { n:'Arcane Lock',            l:2, s:'Abjuration',    ct:'1 Action',       r:'Touch',               d:'Until dispelled',        c:false, ri:false, co:'VSM' },
  { n:'Augury',                 l:2, s:'Divination',    ct:'1 minute',       r:'Self',                d:'Instantaneous',          c:false, ri:true,  co:'VSM' },
  { n:'Barkskin',               l:2, s:'Transmutation', ct:'1 Action',       r:'Touch',               d:'Conc., up to 1 hour',    c:true,  ri:false, co:'VSM' },
  { n:'Beast Sense',            l:2, s:'Divination',    ct:'1 Action',       r:'Touch',               d:'Conc., up to 1 hour',    c:true,  ri:true,  co:'S'   },
  { n:'Blindness/Deafness',     l:2, s:'Necromancy',    ct:'1 Action',       r:'30 ft.',              d:'1 minute',               c:false, ri:false, co:'V'   },
  { n:'Blur',                   l:2, s:'Illusion',      ct:'1 Action',       r:'Self',                d:'Conc., up to 1 min.',    c:true,  ri:false, co:'V'   },
  { n:'Calm Emotions',          l:2, s:'Enchantment',   ct:'1 Action',       r:'60 ft.',              d:'Conc., up to 1 min.',    c:true,  ri:false, co:'VS'  },
  { n:'Cloud of Daggers',       l:2, s:'Conjuration',   ct:'1 Action',       r:'60 ft.',              d:'Conc., up to 1 min.',    c:true,  ri:false, co:'VSM' },
  { n:'Continual Flame',        l:2, s:'Evocation',     ct:'1 Action',       r:'Touch',               d:'Until dispelled',        c:false, ri:false, co:'VSM' },
  { n:'Crown of Madness',       l:2, s:'Enchantment',   ct:'1 Action',       r:'120 ft.',             d:'Conc., up to 1 min.',    c:true,  ri:false, co:'VS'  },
  { n:'Darkness',               l:2, s:'Evocation',     ct:'1 Action',       r:'60 ft.',              d:'Conc., up to 10 min.',   c:true,  ri:false, co:'VSM' },
  { n:'Darkvision',             l:2, s:'Transmutation', ct:'1 Action',       r:'Touch',               d:'8 hours',                c:false, ri:false, co:'VSM' },
  { n:'Detect Thoughts',        l:2, s:'Divination',    ct:'1 Action',       r:'Self',                d:'Conc., up to 1 min.',    c:true,  ri:false, co:'VSM' },
  { n:'Enhance Ability',        l:2, s:'Transmutation', ct:'1 Action',       r:'Touch',               d:'Conc., up to 1 hour',    c:true,  ri:false, co:'VSM' },
  { n:'Enlarge/Reduce',         l:2, s:'Transmutation', ct:'1 Action',       r:'30 ft.',              d:'Conc., up to 1 min.',    c:true,  ri:false, co:'VSM' },
  { n:'Enthrall',               l:2, s:'Enchantment',   ct:'1 Action',       r:'60 ft.',              d:'1 minute',               c:false, ri:false, co:'VS'  },
  { n:'Find Steed',             l:2, s:'Conjuration',   ct:'10 minutes',     r:'30 ft.',              d:'Instantaneous',          c:false, ri:false, co:'VS'  },
  { n:'Find Traps',             l:2, s:'Divination',    ct:'1 Action',       r:'120 ft.',             d:'Instantaneous',          c:false, ri:false, co:'VS'  },
  { n:'Flame Blade',            l:2, s:'Evocation',     ct:'Bonus Action',   r:'Self',                d:'Conc., up to 10 min.',   c:true,  ri:false, co:'VSM' },
  { n:'Flaming Sphere',         l:2, s:'Conjuration',   ct:'1 Action',       r:'60 ft.',              d:'Conc., up to 1 min.',    c:true,  ri:false, co:'VSM' },
  { n:'Gentle Repose',          l:2, s:'Necromancy',    ct:'1 Action',       r:'Touch',               d:'10 days',                c:false, ri:true,  co:'VSM' },
  { n:'Gust of Wind',           l:2, s:'Evocation',     ct:'1 Action',       r:'Self (60-ft. line)',  d:'Conc., up to 1 min.',    c:true,  ri:false, co:'VSM' },
  { n:'Hold Person',            l:2, s:'Enchantment',   ct:'1 Action',       r:'60 ft.',              d:'Conc., up to 1 min.',    c:true,  ri:false, co:'VSM' },
  { n:'Invisibility',           l:2, s:'Illusion',      ct:'1 Action',       r:'Touch',               d:'Conc., up to 1 hour',    c:true,  ri:false, co:'VSM' },
  { n:'Knock',                  l:2, s:'Transmutation', ct:'1 Action',       r:'60 ft.',              d:'Instantaneous',          c:false, ri:false, co:'V'   },
  { n:'Lesser Restoration',     l:2, s:'Abjuration',    ct:'1 Action',       r:'Touch',               d:'Instantaneous',          c:false, ri:false, co:'VS'  },
  { n:'Levitate',               l:2, s:'Transmutation', ct:'1 Action',       r:'60 ft.',              d:'Conc., up to 10 min.',   c:true,  ri:false, co:'VSM' },
  { n:'Locate Animals or Plants',l:2,s:'Divination',    ct:'1 Action',       r:'Self',                d:'Instantaneous',          c:false, ri:true,  co:'VSM' },
  { n:'Locate Object',          l:2, s:'Divination',    ct:'1 Action',       r:'Self',                d:'Conc., up to 10 min.',   c:true,  ri:false, co:'VSM' },
  { n:'Magic Mouth',            l:2, s:'Illusion',      ct:'1 minute',       r:'30 ft.',              d:'Until dispelled',        c:false, ri:true,  co:'VSM' },
  { n:'Magic Weapon',           l:2, s:'Transmutation', ct:'Bonus Action',   r:'Touch',               d:'Conc., up to 1 hour',    c:true,  ri:false, co:'VS'  },
  { n:"Melf's Acid Arrow",      l:2, s:'Evocation',     ct:'1 Action',       r:'90 ft.',              d:'Instantaneous',          c:false, ri:false, co:'VSM' },
  { n:'Mirror Image',           l:2, s:'Illusion',      ct:'1 Action',       r:'Self',                d:'1 minute',               c:false, ri:false, co:'VS'  },
  { n:'Misty Step',             l:2, s:'Conjuration',   ct:'Bonus Action',   r:'Self',                d:'Instantaneous',          c:false, ri:false, co:'V'   },
  { n:'Moonbeam',               l:2, s:'Evocation',     ct:'1 Action',       r:'120 ft.',             d:'Conc., up to 1 min.',    c:true,  ri:false, co:'VSM' },
  { n:'Pass without Trace',     l:2, s:'Abjuration',    ct:'1 Action',       r:'Self',                d:'Conc., up to 1 hour',    c:true,  ri:false, co:'VSM' },
  { n:'Phantasmal Force',       l:2, s:'Illusion',      ct:'1 Action',       r:'60 ft.',              d:'Conc., up to 1 min.',    c:true,  ri:false, co:'VSM' },
  { n:'Prayer of Healing',      l:2, s:'Evocation',     ct:'10 minutes',     r:'30 ft.',              d:'Instantaneous',          c:false, ri:false, co:'V'   },
  { n:'Protection from Poison', l:2, s:'Abjuration',    ct:'1 Action',       r:'Touch',               d:'1 hour',                 c:false, ri:false, co:'VS'  },
  { n:'Ray of Enfeeblement',    l:2, s:'Necromancy',    ct:'1 Action',       r:'60 ft.',              d:'Conc., up to 1 min.',    c:true,  ri:false, co:'VS'  },
  { n:'Rope Trick',             l:2, s:'Transmutation', ct:'1 Action',       r:'Touch',               d:'1 hour',                 c:false, ri:false, co:'VSM' },
  { n:'See Invisibility',       l:2, s:'Divination',    ct:'1 Action',       r:'Self',                d:'1 hour',                 c:false, ri:false, co:'VSM' },
  { n:'Shatter',                l:2, s:'Evocation',     ct:'1 Action',       r:'60 ft.',              d:'Instantaneous',          c:false, ri:false, co:'VSM' },
  { n:'Silence',                l:2, s:'Illusion',      ct:'1 Action',       r:'120 ft.',             d:'Conc., up to 10 min.',   c:true,  ri:true,  co:'VS'  },
  { n:'Spider Climb',           l:2, s:'Transmutation', ct:'1 Action',       r:'Touch',               d:'Conc., up to 1 hour',    c:true,  ri:false, co:'VSM' },
  { n:'Spike Growth',           l:2, s:'Transmutation', ct:'1 Action',       r:'150 ft.',             d:'Conc., up to 10 min.',   c:true,  ri:false, co:'VSM' },
  { n:'Spiritual Weapon',       l:2, s:'Evocation',     ct:'Bonus Action',   r:'60 ft.',              d:'1 minute',               c:false, ri:false, co:'VS'  },
  { n:'Suggestion',             l:2, s:'Enchantment',   ct:'1 Action',       r:'30 ft.',              d:'Conc., up to 8 hours',   c:true,  ri:false, co:'VSM' },
  { n:'Warding Bond',           l:2, s:'Abjuration',    ct:'1 Action',       r:'Touch',               d:'1 hour',                 c:false, ri:false, co:'VSM' },
  { n:'Web',                    l:2, s:'Conjuration',   ct:'1 Action',       r:'60 ft.',              d:'Conc., up to 1 hour',    c:true,  ri:false, co:'VSM' },
  { n:'Zone of Truth',          l:2, s:'Enchantment',   ct:'1 Action',       r:'60 ft.',              d:'10 minutes',             c:false, ri:false, co:'VS'  },

  // ── Level 3 ───────────────────────────────────────────────
  { n:'Animate Dead',             l:3, s:'Necromancy',    ct:'1 minute',       r:'10 ft.',                    d:'24 hours',               c:false, ri:false, co:'VSM' },
  { n:'Aura of Vitality',         l:3, s:'Evocation',     ct:'1 Action',       r:'Self (30-ft. radius)',       d:'Conc., up to 1 min.',    c:true,  ri:false, co:'V'   },
  { n:'Beacon of Hope',           l:3, s:'Abjuration',    ct:'1 Action',       r:'30 ft.',                    d:'Conc., up to 1 min.',    c:true,  ri:false, co:'VS'  },
  { n:'Bestow Curse',             l:3, s:'Necromancy',    ct:'1 Action',       r:'Touch',                     d:'Conc., up to 1 min.',    c:true,  ri:false, co:'VS'  },
  { n:'Blink',                    l:3, s:'Transmutation', ct:'1 Action',       r:'Self',                      d:'1 minute',               c:false, ri:false, co:'VS'  },
  { n:'Call Lightning',           l:3, s:'Conjuration',   ct:'1 Action',       r:'120 ft.',                   d:'Conc., up to 10 min.',   c:true,  ri:false, co:'VS'  },
  { n:'Clairvoyance',             l:3, s:'Divination',    ct:'10 minutes',     r:'1 mile',                    d:'Conc., up to 10 min.',   c:true,  ri:false, co:'VSM' },
  { n:'Conjure Animals',          l:3, s:'Conjuration',   ct:'1 Action',       r:'60 ft.',                    d:'Conc., up to 1 hour',    c:true,  ri:false, co:'VS'  },
  { n:'Counterspell',             l:3, s:'Abjuration',    ct:'1 Reaction',     r:'60 ft.',                    d:'Instantaneous',          c:false, ri:false, co:'S'   },
  { n:'Create Food and Water',    l:3, s:'Conjuration',   ct:'1 Action',       r:'30 ft.',                    d:'Instantaneous',          c:false, ri:false, co:'VS'  },
  { n:'Daylight',                 l:3, s:'Evocation',     ct:'1 Action',       r:'60 ft.',                    d:'1 hour',                 c:false, ri:false, co:'VS'  },
  { n:'Dispel Magic',             l:3, s:'Abjuration',    ct:'1 Action',       r:'120 ft.',                   d:'Instantaneous',          c:false, ri:false, co:'VS'  },
  { n:'Fear',                     l:3, s:'Illusion',      ct:'1 Action',       r:'Self (30-ft. cone)',         d:'Conc., up to 1 min.',    c:true,  ri:false, co:'VSM' },
  { n:'Feign Death',              l:3, s:'Necromancy',    ct:'1 Action',       r:'Touch',                     d:'1 hour',                 c:false, ri:true,  co:'VSM' },
  { n:'Fireball',                 l:3, s:'Evocation',     ct:'1 Action',       r:'150 ft.',                   d:'Instantaneous',          c:false, ri:false, co:'VSM' },
  { n:'Fly',                      l:3, s:'Transmutation', ct:'1 Action',       r:'Touch',                     d:'Conc., up to 10 min.',   c:true,  ri:false, co:'VSM' },
  { n:'Gaseous Form',             l:3, s:'Transmutation', ct:'1 Action',       r:'Touch',                     d:'Conc., up to 1 hour',    c:true,  ri:false, co:'VSM' },
  { n:'Glyph of Warding',         l:3, s:'Abjuration',    ct:'1 hour',         r:'Touch',                     d:'Until dispelled',        c:false, ri:false, co:'VSM' },
  { n:'Haste',                    l:3, s:'Transmutation', ct:'1 Action',       r:'30 ft.',                    d:'Conc., up to 1 min.',    c:true,  ri:false, co:'VSM' },
  { n:'Hypnotic Pattern',         l:3, s:'Illusion',      ct:'1 Action',       r:'120 ft.',                   d:'Conc., up to 1 min.',    c:true,  ri:false, co:'SM'  },
  { n:"Leomund's Tiny Hut",       l:3, s:'Evocation',     ct:'1 minute',       r:'Self (10-ft. radius)',       d:'8 hours',                c:false, ri:true,  co:'VSM' },
  { n:'Lightning Bolt',           l:3, s:'Evocation',     ct:'1 Action',       r:'Self (100-ft. line)',        d:'Instantaneous',          c:false, ri:false, co:'VSM' },
  { n:'Magic Circle',             l:3, s:'Abjuration',    ct:'1 minute',       r:'10 ft.',                    d:'1 hour',                 c:false, ri:false, co:'VSM' },
  { n:'Major Image',              l:3, s:'Illusion',      ct:'1 Action',       r:'120 ft.',                   d:'Conc., up to 10 min.',   c:true,  ri:false, co:'VSM' },
  { n:'Mass Healing Word',        l:3, s:'Evocation',     ct:'Bonus Action',   r:'60 ft.',                    d:'Instantaneous',          c:false, ri:false, co:'V'   },
  { n:'Meld into Stone',          l:3, s:'Transmutation', ct:'1 Action',       r:'Touch',                     d:'8 hours',                c:false, ri:true,  co:'VS'  },
  { n:'Nondetection',             l:3, s:'Abjuration',    ct:'1 Action',       r:'Touch',                     d:'8 hours',                c:false, ri:false, co:'VSM' },
  { n:'Phantom Steed',            l:3, s:'Illusion',      ct:'1 minute',       r:'30 ft.',                    d:'1 hour',                 c:false, ri:true,  co:'VS'  },
  { n:'Plant Growth',             l:3, s:'Transmutation', ct:'1 Action',       r:'150 ft.',                   d:'Instantaneous',          c:false, ri:false, co:'VS'  },
  { n:'Protection from Energy',   l:3, s:'Abjuration',    ct:'1 Action',       r:'Touch',                     d:'Conc., up to 1 hour',    c:true,  ri:false, co:'VS'  },
  { n:'Remove Curse',             l:3, s:'Abjuration',    ct:'1 Action',       r:'Touch',                     d:'Instantaneous',          c:false, ri:false, co:'VS'  },
  { n:'Revivify',                 l:3, s:'Conjuration',   ct:'1 Action',       r:'Touch',                     d:'Instantaneous',          c:false, ri:false, co:'VSM' },
  { n:'Sending',                  l:3, s:'Evocation',     ct:'1 Action',       r:'Unlimited',                 d:'1 round',                c:false, ri:false, co:'VSM' },
  { n:'Sleet Storm',              l:3, s:'Conjuration',   ct:'1 Action',       r:'150 ft.',                   d:'Conc., up to 1 min.',    c:true,  ri:false, co:'VSM' },
  { n:'Slow',                     l:3, s:'Transmutation', ct:'1 Action',       r:'120 ft.',                   d:'Conc., up to 1 min.',    c:true,  ri:false, co:'VSM' },
  { n:'Speak with Dead',          l:3, s:'Necromancy',    ct:'1 Action',       r:'10 ft.',                    d:'10 minutes',             c:false, ri:false, co:'VSM' },
  { n:'Speak with Plants',        l:3, s:'Transmutation', ct:'1 Action',       r:'Self (30-ft. radius)',       d:'10 minutes',             c:false, ri:false, co:'VS'  },
  { n:'Spirit Guardians',         l:3, s:'Conjuration',   ct:'1 Action',       r:'Self (15-ft. radius)',       d:'Conc., up to 10 min.',   c:true,  ri:false, co:'VSM' },
  { n:'Stinking Cloud',           l:3, s:'Conjuration',   ct:'1 Action',       r:'90 ft.',                    d:'Conc., up to 1 min.',    c:true,  ri:false, co:'VSM' },
  { n:'Tongues',                  l:3, s:'Divination',    ct:'1 Action',       r:'Touch',                     d:'1 hour',                 c:false, ri:false, co:'VSM' },
  { n:'Vampiric Touch',           l:3, s:'Necromancy',    ct:'1 Action',       r:'Self',                      d:'Conc., up to 1 min.',    c:true,  ri:false, co:'VS'  },
  { n:'Water Breathing',          l:3, s:'Transmutation', ct:'1 Action',       r:'30 ft.',                    d:'24 hours',               c:false, ri:true,  co:'VSM' },
  { n:'Water Walk',               l:3, s:'Transmutation', ct:'1 Action',       r:'30 ft.',                    d:'1 hour',                 c:false, ri:true,  co:'VSM' },
  { n:'Wind Wall',                l:3, s:'Evocation',     ct:'1 Action',       r:'120 ft.',                   d:'Conc., up to 1 min.',    c:true,  ri:false, co:'VSM' },

  // ── Level 4 ───────────────────────────────────────────────
  { n:'Arcane Eye',                    l:4, s:'Divination',    ct:'1 Action',       r:'30 ft.',    d:'Conc., up to 1 hour',    c:true,  ri:false, co:'VSM' },
  { n:'Banishment',                    l:4, s:'Abjuration',    ct:'1 Action',       r:'60 ft.',    d:'Conc., up to 1 min.',    c:true,  ri:false, co:'VSM' },
  { n:'Blight',                        l:4, s:'Necromancy',    ct:'1 Action',       r:'30 ft.',    d:'Instantaneous',          c:false, ri:false, co:'VS'  },
  { n:'Compulsion',                    l:4, s:'Enchantment',   ct:'1 Action',       r:'30 ft.',    d:'Conc., up to 1 min.',    c:true,  ri:false, co:'VS'  },
  { n:'Confusion',                     l:4, s:'Enchantment',   ct:'1 Action',       r:'90 ft.',    d:'Conc., up to 1 min.',    c:true,  ri:false, co:'VSM' },
  { n:'Conjure Minor Elementals',      l:4, s:'Conjuration',   ct:'1 minute',       r:'90 ft.',    d:'Conc., up to 1 hour',    c:true,  ri:false, co:'VS'  },
  { n:'Conjure Woodland Beings',       l:4, s:'Conjuration',   ct:'1 Action',       r:'60 ft.',    d:'Conc., up to 1 hour',    c:true,  ri:false, co:'VSM' },
  { n:'Control Water',                 l:4, s:'Transmutation', ct:'1 Action',       r:'300 ft.',   d:'Conc., up to 10 min.',   c:true,  ri:false, co:'VSM' },
  { n:'Death Ward',                    l:4, s:'Abjuration',    ct:'1 Action',       r:'Touch',     d:'8 hours',                c:false, ri:false, co:'VS'  },
  { n:'Dimension Door',                l:4, s:'Conjuration',   ct:'1 Action',       r:'500 ft.',   d:'Instantaneous',          c:false, ri:false, co:'V'   },
  { n:'Divination',                    l:4, s:'Divination',    ct:'1 Action',       r:'Self',      d:'Instantaneous',          c:false, ri:true,  co:'VSM' },
  { n:'Dominate Beast',                l:4, s:'Enchantment',   ct:'1 Action',       r:'60 ft.',    d:'Conc., up to 1 min.',    c:true,  ri:false, co:'VS'  },
  { n:"Evard's Black Tentacles",       l:4, s:'Conjuration',   ct:'1 Action',       r:'90 ft.',    d:'Conc., up to 1 min.',    c:true,  ri:false, co:'VSM' },
  { n:'Fabricate',                     l:4, s:'Transmutation', ct:'10 minutes',     r:'120 ft.',   d:'Instantaneous',          c:false, ri:false, co:'VS'  },
  { n:'Fire Shield',                   l:4, s:'Evocation',     ct:'1 Action',       r:'Self',      d:'10 minutes',             c:false, ri:false, co:'VSM' },
  { n:'Freedom of Movement',           l:4, s:'Abjuration',    ct:'1 Action',       r:'Touch',     d:'1 hour',                 c:false, ri:false, co:'VSM' },
  { n:'Giant Insect',                  l:4, s:'Transmutation', ct:'1 Action',       r:'30 ft.',    d:'Conc., up to 10 min.',   c:true,  ri:false, co:'VS'  },
  { n:'Greater Invisibility',          l:4, s:'Illusion',      ct:'1 Action',       r:'Touch',     d:'Conc., up to 1 min.',    c:true,  ri:false, co:'VS'  },
  { n:'Guardian of Faith',             l:4, s:'Conjuration',   ct:'1 Action',       r:'30 ft.',    d:'8 hours',                c:false, ri:false, co:'V'   },
  { n:'Hallucinatory Terrain',         l:4, s:'Illusion',      ct:'10 minutes',     r:'300 ft.',   d:'24 hours',               c:false, ri:false, co:'VSM' },
  { n:'Ice Storm',                     l:4, s:'Evocation',     ct:'1 Action',       r:'300 ft.',   d:'Instantaneous',          c:false, ri:false, co:'VSM' },
  { n:"Leomund's Secret Chest",        l:4, s:'Conjuration',   ct:'1 Action',       r:'Touch',     d:'Instantaneous',          c:false, ri:false, co:'VSM' },
  { n:'Locate Creature',               l:4, s:'Divination',    ct:'1 Action',       r:'Self',      d:'Conc., up to 1 hour',    c:true,  ri:false, co:'VSM' },
  { n:"Mordenkainen's Faithful Hound", l:4, s:'Conjuration',   ct:'1 Action',       r:'30 ft.',    d:'8 hours',                c:false, ri:false, co:'VSM' },
  { n:"Mordenkainen's Private Sanctum",l:4, s:'Abjuration',    ct:'10 minutes',     r:'120 ft.',   d:'24 hours',               c:false, ri:false, co:'VSM' },
  { n:"Otiluke's Resilient Sphere",    l:4, s:'Evocation',     ct:'1 Action',       r:'30 ft.',    d:'Conc., up to 1 min.',    c:true,  ri:false, co:'VSM' },
  { n:'Phantasmal Killer',             l:4, s:'Illusion',      ct:'1 Action',       r:'120 ft.',   d:'Conc., up to 1 min.',    c:true,  ri:false, co:'VS'  },
  { n:'Polymorph',                     l:4, s:'Transmutation', ct:'1 Action',       r:'60 ft.',    d:'Conc., up to 1 hour',    c:true,  ri:false, co:'VSM' },
  { n:'Stone Shape',                   l:4, s:'Transmutation', ct:'1 Action',       r:'Touch',     d:'Instantaneous',          c:false, ri:false, co:'VSM' },
  { n:'Stoneskin',                     l:4, s:'Abjuration',    ct:'1 Action',       r:'Touch',     d:'Conc., up to 1 hour',    c:true,  ri:false, co:'VSM' },
  { n:'Wall of Fire',                  l:4, s:'Evocation',     ct:'1 Action',       r:'120 ft.',   d:'Conc., up to 1 min.',    c:true,  ri:false, co:'VSM' },

  // ── Level 5 ───────────────────────────────────────────────
  { n:'Animate Objects',          l:5, s:'Transmutation', ct:'1 Action',       r:'120 ft.',   d:'Conc., up to 1 min.',    c:true,  ri:false, co:'VS'  },
  { n:'Antilife Shell',           l:5, s:'Abjuration',    ct:'1 Action',       r:'Self (10-ft. radius)', d:'Conc., up to 1 hour', c:true, ri:false, co:'VS' },
  { n:'Arcane Hand',              l:5, s:'Evocation',     ct:'1 Action',       r:'120 ft.',   d:'Conc., up to 1 min.',    c:true,  ri:false, co:'VSM' },
  { n:'Awaken',                   l:5, s:'Transmutation', ct:'8 hours',        r:'Touch',     d:'Instantaneous',          c:false, ri:false, co:'VSM' },
  { n:'Cloudkill',                l:5, s:'Conjuration',   ct:'1 Action',       r:'120 ft.',   d:'Conc., up to 10 min.',   c:true,  ri:false, co:'VS'  },
  { n:'Commune',                  l:5, s:'Divination',    ct:'1 minute',       r:'Self',      d:'1 minute',               c:false, ri:true,  co:'VSM' },
  { n:'Commune with Nature',      l:5, s:'Divination',    ct:'1 minute',       r:'Self',      d:'Instantaneous',          c:false, ri:true,  co:'VS'  },
  { n:'Cone of Cold',             l:5, s:'Evocation',     ct:'1 Action',       r:'Self (60-ft. cone)', d:'Instantaneous', c:false, ri:false, co:'VSM' },
  { n:'Conjure Elemental',        l:5, s:'Conjuration',   ct:'1 minute',       r:'90 ft.',    d:'Conc., up to 1 hour',    c:true,  ri:false, co:'VSM' },
  { n:'Contact Other Plane',      l:5, s:'Divination',    ct:'1 minute',       r:'Self',      d:'1 minute',               c:false, ri:true,  co:'V'   },
  { n:'Contagion',                l:5, s:'Necromancy',    ct:'1 Action',       r:'Touch',     d:'7 days',                 c:false, ri:false, co:'VS'  },
  { n:'Creation',                 l:5, s:'Illusion',      ct:'1 minute',       r:'30 ft.',    d:'Special',                c:false, ri:false, co:'VSM' },
  { n:'Dispel Evil and Good',     l:5, s:'Abjuration',    ct:'1 Action',       r:'Self',      d:'Conc., up to 1 min.',    c:true,  ri:false, co:'VS'  },
  { n:'Dominate Person',          l:5, s:'Enchantment',   ct:'1 Action',       r:'60 ft.',    d:'Conc., up to 1 min.',    c:true,  ri:false, co:'VS'  },
  { n:'Dream',                    l:5, s:'Illusion',      ct:'1 minute',       r:'Special',   d:'8 hours',                c:false, ri:false, co:'VSM' },
  { n:'Flame Strike',             l:5, s:'Evocation',     ct:'1 Action',       r:'60 ft.',    d:'Instantaneous',          c:false, ri:false, co:'VS'  },
  { n:'Geas',                     l:5, s:'Enchantment',   ct:'1 minute',       r:'60 ft.',    d:'30 days',                c:false, ri:false, co:'V'   },
  { n:'Greater Restoration',      l:5, s:'Abjuration',    ct:'1 Action',       r:'Touch',     d:'Instantaneous',          c:false, ri:false, co:'VSM' },
  { n:'Hold Monster',             l:5, s:'Enchantment',   ct:'1 Action',       r:'90 ft.',    d:'Conc., up to 1 min.',    c:true,  ri:false, co:'VSM' },
  { n:'Insect Plague',            l:5, s:'Conjuration',   ct:'1 Action',       r:'300 ft.',   d:'Conc., up to 10 min.',   c:true,  ri:false, co:'VSM' },
  { n:'Legend Lore',              l:5, s:'Divination',    ct:'10 minutes',     r:'Self',      d:'Instantaneous',          c:false, ri:false, co:'VSM' },
  { n:'Mass Cure Wounds',         l:5, s:'Evocation',     ct:'1 Action',       r:'60 ft.',    d:'Instantaneous',          c:false, ri:false, co:'VS'  },
  { n:'Mislead',                  l:5, s:'Illusion',      ct:'1 Action',       r:'Self',      d:'Conc., up to 1 hour',    c:true,  ri:false, co:'S'   },
  { n:'Modify Memory',            l:5, s:'Enchantment',   ct:'1 Action',       r:'30 ft.',    d:'Conc., up to 1 min.',    c:true,  ri:false, co:'VS'  },
  { n:'Passwall',                 l:5, s:'Transmutation', ct:'1 Action',       r:'30 ft.',    d:'1 hour',                 c:false, ri:false, co:'VSM' },
  { n:'Planar Binding',           l:5, s:'Abjuration',    ct:'1 hour',         r:'60 ft.',    d:'24 hours',               c:false, ri:false, co:'VSM' },
  { n:'Raise Dead',               l:5, s:'Necromancy',    ct:'1 hour',         r:'Touch',     d:'Instantaneous',          c:false, ri:false, co:'VSM' },
  { n:"Rary's Telepathic Bond",   l:5, s:'Divination',    ct:'1 Action',       r:'30 ft.',    d:'1 hour',                 c:false, ri:true,  co:'VSM' },
  { n:'Reincarnate',              l:5, s:'Transmutation', ct:'1 hour',         r:'Touch',     d:'Instantaneous',          c:false, ri:false, co:'VSM' },
  { n:'Scrying',                  l:5, s:'Divination',    ct:'10 minutes',     r:'Self',      d:'Conc., up to 10 min.',   c:true,  ri:false, co:'VSM' },
  { n:'Seeming',                  l:5, s:'Illusion',      ct:'1 Action',       r:'30 ft.',    d:'8 hours',                c:false, ri:false, co:'VS'  },
  { n:'Swift Quiver',             l:5, s:'Transmutation', ct:'Bonus Action',   r:'Touch',     d:'Conc., up to 1 min.',    c:true,  ri:false, co:'VSM' },
  { n:'Telekinesis',              l:5, s:'Transmutation', ct:'1 Action',       r:'60 ft.',    d:'Conc., up to 10 min.',   c:true,  ri:false, co:'VS'  },
  { n:'Teleportation Circle',     l:5, s:'Conjuration',   ct:'1 minute',       r:'10 ft.',    d:'1 round',                c:false, ri:false, co:'VSM' },
  { n:'Tree Stride',              l:5, s:'Conjuration',   ct:'1 Action',       r:'Self',      d:'Conc., up to 1 min.',    c:true,  ri:false, co:'VS'  },
  { n:'Wall of Force',            l:5, s:'Evocation',     ct:'1 Action',       r:'120 ft.',   d:'Conc., up to 10 min.',   c:true,  ri:false, co:'VSM' },
  { n:'Wall of Stone',            l:5, s:'Evocation',     ct:'1 Action',       r:'120 ft.',   d:'Conc., up to 10 min.',   c:true,  ri:false, co:'VSM' },

  // ── Level 6 ───────────────────────────────────────────────
  { n:'Arcane Gate',          l:6, s:'Conjuration',   ct:'1 Action',       r:'500 ft.',   d:'Conc., up to 10 min.',   c:true,  ri:false, co:'VSM' },
  { n:'Blade Barrier',        l:6, s:'Evocation',     ct:'1 Action',       r:'90 ft.',    d:'Conc., up to 10 min.',   c:true,  ri:false, co:'VS'  },
  { n:'Chain Lightning',      l:6, s:'Evocation',     ct:'1 Action',       r:'150 ft.',   d:'Instantaneous',          c:false, ri:false, co:'VSM' },
  { n:'Circle of Death',      l:6, s:'Necromancy',    ct:'1 Action',       r:'150 ft.',   d:'Instantaneous',          c:false, ri:false, co:'VSM' },
  { n:'Conjure Fey',          l:6, s:'Conjuration',   ct:'1 minute',       r:'90 ft.',    d:'Conc., up to 1 hour',    c:true,  ri:false, co:'VS'  },
  { n:'Contingency',          l:6, s:'Evocation',     ct:'10 minutes',     r:'Self',      d:'10 days',                c:false, ri:false, co:'VSM' },
  { n:'Create Undead',        l:6, s:'Necromancy',    ct:'1 minute',       r:'10 ft.',    d:'Instantaneous',          c:false, ri:false, co:'VSM' },
  { n:'Eyebite',              l:6, s:'Necromancy',    ct:'1 Action',       r:'Self',      d:'Conc., up to 1 min.',    c:true,  ri:false, co:'VS'  },
  { n:'Find the Path',        l:6, s:'Divination',    ct:'1 minute',       r:'Self',      d:'Conc., up to 1 day',     c:true,  ri:false, co:'VSM' },
  { n:'Flesh to Stone',       l:6, s:'Transmutation', ct:'1 Action',       r:'60 ft.',    d:'Conc., up to 1 min.',    c:true,  ri:false, co:'VSM' },
  { n:'Globe of Invulnerability',l:6,s:'Abjuration',  ct:'1 Action',       r:'Self (10-ft. radius)', d:'Conc., up to 1 min.', c:true, ri:false, co:'VSM' },
  { n:'Guards and Wards',     l:6, s:'Abjuration',    ct:'10 minutes',     r:'Touch',     d:'24 hours',               c:false, ri:false, co:'VSM' },
  { n:'Harm',                 l:6, s:'Necromancy',    ct:'1 Action',       r:'60 ft.',    d:'Instantaneous',          c:false, ri:false, co:'VS'  },
  { n:'Heal',                 l:6, s:'Evocation',     ct:'1 Action',       r:'60 ft.',    d:'Instantaneous',          c:false, ri:false, co:'VS'  },
  { n:"Heroes' Feast",        l:6, s:'Conjuration',   ct:'10 minutes',     r:'30 ft.',    d:'Instantaneous',          c:false, ri:false, co:'VSM' },
  { n:'Move Earth',           l:6, s:'Transmutation', ct:'1 Action',       r:'120 ft.',   d:'Conc., up to 2 hours',   c:true,  ri:false, co:'VSM' },
  { n:"Otto's Irresistible Dance",l:6,s:'Enchantment', ct:'1 Action',      r:'30 ft.',    d:'Conc., up to 1 min.',    c:true,  ri:false, co:'V'   },
  { n:'Planar Ally',          l:6, s:'Conjuration',   ct:'10 minutes',     r:'60 ft.',    d:'Instantaneous',          c:false, ri:false, co:'VS'  },
  { n:'Programmed Illusion',  l:6, s:'Illusion',      ct:'1 Action',       r:'120 ft.',   d:'Until dispelled',        c:false, ri:false, co:'VSM' },
  { n:'Sunbeam',              l:6, s:'Evocation',     ct:'1 Action',       r:'Self (60-ft. line)', d:'Conc., up to 1 min.', c:true, ri:false, co:'VSM' },
  { n:'Transport via Plants', l:6, s:'Conjuration',   ct:'1 Action',       r:'10 ft.',    d:'1 round',                c:false, ri:false, co:'VS'  },
  { n:'True Seeing',          l:6, s:'Divination',    ct:'1 Action',       r:'Touch',     d:'1 hour',                 c:false, ri:false, co:'VSM' },
  { n:'Wall of Ice',          l:6, s:'Evocation',     ct:'1 Action',       r:'120 ft.',   d:'Conc., up to 10 min.',   c:true,  ri:false, co:'VSM' },
  { n:'Wall of Thorns',       l:6, s:'Conjuration',   ct:'1 Action',       r:'120 ft.',   d:'Conc., up to 10 min.',   c:true,  ri:false, co:'VSM' },
  { n:'Wind Walk',            l:6, s:'Transmutation', ct:'1 minute',       r:'30 ft.',    d:'8 hours',                c:false, ri:false, co:'VS'  },
  { n:'Word of Recall',       l:6, s:'Conjuration',   ct:'1 Action',       r:'5 ft.',     d:'Instantaneous',          c:false, ri:false, co:'V'   },

  // ── Level 7 ───────────────────────────────────────────────
  { n:'Conjure Celestial',                    l:7, s:'Conjuration',   ct:'1 minute',       r:'90 ft.',    d:'Conc., up to 1 hour',    c:true,  ri:false, co:'VS'  },
  { n:'Delayed Blast Fireball',               l:7, s:'Evocation',     ct:'1 Action',       r:'150 ft.',   d:'Conc., up to 1 min.',    c:true,  ri:false, co:'VSM' },
  { n:'Divine Word',                          l:7, s:'Evocation',     ct:'Bonus Action',   r:'30 ft.',    d:'Instantaneous',          c:false, ri:false, co:'V'   },
  { n:'Etherealness',                         l:7, s:'Transmutation', ct:'1 Action',       r:'Self',      d:'Up to 8 hours',          c:false, ri:false, co:'VS'  },
  { n:'Fire Storm',                           l:7, s:'Evocation',     ct:'1 Action',       r:'150 ft.',   d:'Instantaneous',          c:false, ri:false, co:'VS'  },
  { n:'Forcecage',                            l:7, s:'Evocation',     ct:'1 Action',       r:'100 ft.',   d:'1 hour',                 c:false, ri:false, co:'VSM' },
  { n:'Mirage Arcane',                        l:7, s:'Illusion',      ct:'10 minutes',     r:'Sight',     d:'10 days',                c:false, ri:false, co:'VS'  },
  { n:"Mordenkainen's Magnificent Mansion",   l:7, s:'Conjuration',   ct:'1 minute',       r:'300 ft.',   d:'24 hours',               c:false, ri:false, co:'VSM' },
  { n:"Mordenkainen's Sword",                 l:7, s:'Evocation',     ct:'1 Action',       r:'60 ft.',    d:'Conc., up to 1 min.',    c:true,  ri:false, co:'VSM' },
  { n:'Plane Shift',                          l:7, s:'Conjuration',   ct:'1 Action',       r:'Touch',     d:'Instantaneous',          c:false, ri:false, co:'VSM' },
  { n:'Prismatic Spray',                      l:7, s:'Evocation',     ct:'1 Action',       r:'Self (60-ft. cone)', d:'Instantaneous', c:false, ri:false, co:'VS'  },
  { n:'Project Image',                        l:7, s:'Illusion',      ct:'1 Action',       r:'500 miles', d:'Conc., up to 1 day',     c:true,  ri:false, co:'VSM' },
  { n:'Regenerate',                           l:7, s:'Transmutation', ct:'1 minute',       r:'Touch',     d:'1 hour',                 c:false, ri:false, co:'VS'  },
  { n:'Resurrection',                         l:7, s:'Necromancy',    ct:'1 hour',         r:'Touch',     d:'Instantaneous',          c:false, ri:false, co:'VSM' },
  { n:'Reverse Gravity',                      l:7, s:'Transmutation', ct:'1 Action',       r:'100 ft.',   d:'Conc., up to 1 min.',    c:true,  ri:false, co:'VSM' },
  { n:'Sequester',                            l:7, s:'Transmutation', ct:'1 Action',       r:'Touch',     d:'Until dispelled',        c:false, ri:false, co:'VSM' },
  { n:'Simulacrum',                           l:7, s:'Illusion',      ct:'12 hours',       r:'Touch',     d:'Until dispelled',        c:false, ri:false, co:'VSM' },
  { n:'Symbol',                               l:7, s:'Abjuration',    ct:'1 minute',       r:'Touch',     d:'Until dispelled',        c:false, ri:false, co:'VSM' },
  { n:'Teleport',                             l:7, s:'Conjuration',   ct:'1 Action',       r:'10 ft.',    d:'Instantaneous',          c:false, ri:false, co:'V'   },

  // ── Level 8 ───────────────────────────────────────────────
  { n:'Animal Shapes',     l:8, s:'Transmutation', ct:'1 Action',       r:'30 ft.',    d:'Conc., up to 24 hours',  c:true,  ri:false, co:'VS'  },
  { n:'Antimagic Field',   l:8, s:'Abjuration',    ct:'1 Action',       r:'Self (10-ft. radius)', d:'Conc., up to 1 hour', c:true, ri:false, co:'VS' },
  { n:'Antipathy/Sympathy',l:8, s:'Enchantment',   ct:'1 hour',         r:'60 ft.',    d:'10 days',                c:false, ri:false, co:'VSM' },
  { n:'Clone',             l:8, s:'Necromancy',    ct:'1 hour',         r:'Touch',     d:'Instantaneous',          c:false, ri:false, co:'VSM' },
  { n:'Control Weather',   l:8, s:'Transmutation', ct:'10 minutes',     r:'Self (5-mile radius)', d:'Conc., up to 8 hours', c:true, ri:false, co:'VS' },
  { n:'Demiplane',         l:8, s:'Conjuration',   ct:'1 Action',       r:'60 ft.',    d:'1 hour',                 c:false, ri:false, co:'S'   },
  { n:'Dominate Monster',  l:8, s:'Enchantment',   ct:'1 Action',       r:'60 ft.',    d:'Conc., up to 1 hour',    c:true,  ri:false, co:'VS'  },
  { n:'Earthquake',        l:8, s:'Evocation',     ct:'1 Action',       r:'500 ft.',   d:'Conc., up to 1 min.',    c:true,  ri:false, co:'VS'  },
  { n:'Feeblemind',        l:8, s:'Enchantment',   ct:'1 Action',       r:'150 ft.',   d:'Instantaneous',          c:false, ri:false, co:'VSM' },
  { n:'Glibness',          l:8, s:'Transmutation', ct:'1 Action',       r:'Self',      d:'1 hour',                 c:false, ri:false, co:'V'   },
  { n:'Holy Aura',         l:8, s:'Abjuration',    ct:'1 Action',       r:'Self (30-ft. radius)', d:'Conc., up to 1 min.', c:true, ri:false, co:'VSM' },
  { n:'Incendiary Cloud',  l:8, s:'Conjuration',   ct:'1 Action',       r:'150 ft.',   d:'Conc., up to 1 min.',    c:true,  ri:false, co:'VS'  },
  { n:'Maze',              l:8, s:'Conjuration',   ct:'1 Action',       r:'60 ft.',    d:'Conc., up to 10 min.',   c:true,  ri:false, co:'VS'  },
  { n:'Mind Blank',        l:8, s:'Abjuration',    ct:'1 Action',       r:'Touch',     d:'24 hours',               c:false, ri:false, co:'VS'  },
  { n:'Power Word Stun',   l:8, s:'Enchantment',   ct:'1 Action',       r:'60 ft.',    d:'Special',                c:false, ri:false, co:'V'   },
  { n:'Sunburst',          l:8, s:'Evocation',     ct:'1 Action',       r:'150 ft.',   d:'Instantaneous',          c:false, ri:false, co:'VSM' },
  { n:'Tsunami',           l:8, s:'Conjuration',   ct:'1 minute',       r:'Sight',     d:'Conc., up to 6 rounds',  c:true,  ri:false, co:'VS'  },

  // ── Level 9 ───────────────────────────────────────────────
  { n:'Astral Projection', l:9, s:'Necromancy',    ct:'1 hour',         r:'10 ft.',    d:'Special',                c:false, ri:false, co:'VSM' },
  { n:'Foresight',         l:9, s:'Divination',    ct:'1 minute',       r:'Touch',     d:'8 hours',                c:false, ri:false, co:'VSM' },
  { n:'Gate',              l:9, s:'Conjuration',   ct:'1 Action',       r:'60 ft.',    d:'Conc., up to 1 min.',    c:true,  ri:false, co:'VSM' },
  { n:'Imprisonment',      l:9, s:'Abjuration',    ct:'1 minute',       r:'30 ft.',    d:'Until dispelled',        c:false, ri:false, co:'VSM' },
  { n:'Mass Heal',         l:9, s:'Evocation',     ct:'1 Action',       r:'60 ft.',    d:'Instantaneous',          c:false, ri:false, co:'VS'  },
  { n:'Meteor Swarm',      l:9, s:'Evocation',     ct:'1 Action',       r:'1 mile',    d:'Instantaneous',          c:false, ri:false, co:'VS'  },
  { n:'Power Word Kill',   l:9, s:'Enchantment',   ct:'1 Action',       r:'60 ft.',    d:'Instantaneous',          c:false, ri:false, co:'V'   },
  { n:'Prismatic Wall',    l:9, s:'Abjuration',    ct:'1 Action',       r:'60 ft.',    d:'10 minutes',             c:false, ri:false, co:'VS'  },
  { n:'Shapechange',       l:9, s:'Transmutation', ct:'1 Action',       r:'Self',      d:'Conc., up to 1 hour',    c:true,  ri:false, co:'VSM' },
  { n:'Storm of Vengeance',l:9, s:'Conjuration',   ct:'1 Action',       r:'Sight',     d:'Conc., up to 10 min.',   c:true,  ri:false, co:'VS'  },
  { n:'Time Stop',         l:9, s:'Transmutation', ct:'1 Action',       r:'Self',      d:'Special',                c:false, ri:false, co:'V'   },
  { n:'True Polymorph',    l:9, s:'Transmutation', ct:'1 Action',       r:'30 ft.',    d:'Conc., up to 1 hour',    c:true,  ri:false, co:'VSM' },
  { n:'True Resurrection', l:9, s:'Necromancy',    ct:'1 hour',         r:'Touch',     d:'Instantaneous',          c:false, ri:false, co:'VSM' },
  { n:'Weird',             l:9, s:'Illusion',      ct:'1 Action',       r:'120 ft.',   d:'Conc., up to 1 min.',    c:true,  ri:false, co:'VS'  },
  { n:'Wish',              l:9, s:'Conjuration',   ct:'1 Action',       r:'Self',      d:'Instantaneous',          c:false, ri:false, co:'V'   },
];

/* ============================================================
   FEATS — SRD 5.1
   ============================================================ */
const SRD_FEATS = [
  { name: 'Alert',               desc: '+5 to initiative. Can\'t be surprised while conscious. Creatures you can\'t see don\'t gain advantage on attack rolls against you.' },
  { name: 'Athlete',             desc: '+1 STR or DEX. Standing up costs only 5 ft. of movement. Climbing doesn\'t cost extra movement. Running long/high jump allowed from standing.' },
  { name: 'Actor',               desc: '+1 CHA. Advantage on Deception/Performance when disguised. Mimic speech and sounds of a creature you\'ve heard.' },
  { name: 'Charger',             desc: 'After Dashing, use a bonus action to melee attack (+5 damage) or shove 10 ft.' },
  { name: 'Crossbow Expert',     desc: 'Ignore Loading. No disadvantage on ranged attacks at close range. Bonus action attack with hand crossbow after Attack action with one-handed weapon.' },
  { name: 'Defensive Duelist',   desc: 'Reaction: add proficiency bonus to AC against one melee hit when wielding a finesse weapon you are proficient with.' },
  { name: 'Dual Wielder',        desc: '+1 AC with two weapons. Two-weapon fight with non-light one-handed weapons. Draw/stow two weapons at once.' },
  { name: 'Dungeon Delver',      desc: 'Advantage on Perception/Investigation for secret doors and traps. Advantage on saves vs. traps. Resistance to trap damage. Search at normal pace.' },
  { name: 'Durable',             desc: '+1 CON. When rolling a Hit Die, minimum result is 2 × your CON modifier (minimum of 2).' },
  { name: 'Elemental Adept',     desc: 'Choose a damage type. Your spells ignore resistance to that type, and treat 1s as 2s on damage dice. Can be taken multiple times.' },
  { name: 'Grappler',            desc: 'Advantage on attack rolls against creatures you are grappling. Use an action to try to pin: both become restrained until grapple ends.' },
  { name: 'Great Weapon Master', desc: 'After crit or reducing a creature to 0 HP, one bonus melee attack. Take −5 to attack roll for +10 damage with heavy weapons.' },
  { name: 'Healer',              desc: 'Stabilize a creature with 1 HP. Use healer\'s kit as action: restore 1d6+4+max HD HP (once per short rest per creature).' },
  { name: 'Heavily Armored',     desc: '+1 STR. Gain proficiency with heavy armor.' },
  { name: 'Heavy Armor Master',  desc: '+1 STR. Reduce non-magical bludgeoning, piercing, and slashing damage by 3 while wearing heavy armor.' },
  { name: 'Inspiring Leader',    desc: '10-min speech grants up to 6 willing creatures within 30 ft. temporary HP equal to your level + CHA modifier.' },
  { name: 'Keen Mind',           desc: '+1 INT. Know the direction of north. Know elapsed time since your last rest. Recall anything you\'ve seen or heard within the past month.' },
  { name: 'Lightly Armored',     desc: '+1 STR or DEX. Gain proficiency with light armor.' },
  { name: 'Linguist',            desc: '+1 INT. Learn 3 languages. Create written ciphers (INT check to decode).' },
  { name: 'Lucky',               desc: '3 luck points per long rest. Spend to gain an extra d20 on an attack roll, ability check, or saving throw, or to impose disadvantage on an attack against you.' },
  { name: 'Mage Slayer',         desc: 'Reaction: melee attack when creature within 5 ft. casts a spell. That creature has disadvantage on concentration saves caused by your attacks. Advantage on saves vs. spells from creatures within 5 ft.' },
  { name: 'Magic Initiate',      desc: 'Choose a class. Learn 2 cantrips and one 1st-level spell from its list. Cast the 1st-level spell once per long rest (using its rules, no slot needed).' },
  { name: 'Martial Adept',       desc: 'Learn 2 maneuvers from the Battle Master list. Gain 1 superiority die (d6) that refreshes on a short or long rest.' },
  { name: 'Medium Armor Master', desc: '+1 STR or DEX. No disadvantage on Stealth in medium armor. Max DEX bonus to AC from medium armor increases to +3.' },
  { name: 'Mobile',              desc: 'Speed +10 ft. Dash in difficult terrain doesn\'t cost extra movement. After attacking a creature, it can\'t make opportunity attacks against you that turn.' },
  { name: 'Moderately Armored',  desc: '+1 STR or DEX. Gain proficiency with medium armor and shields.' },
  { name: 'Mounted Combatant',   desc: 'Advantage on melee attacks vs. unmounted creatures smaller than mount. Redirect attacks targeting mount to yourself. Mount has advantage on DEX saves and takes no damage on a successful save.' },
  { name: 'Observant',           desc: '+1 INT or WIS. Lip-read creatures within 10 ft. that you can see. +5 to passive Perception and passive Investigation.' },
  { name: 'Polearm Master',      desc: 'Bonus action butt-end attack (1d4 bludgeoning) after Attack action with a polearm. Opportunity attacks when creatures enter your reach.' },
  { name: 'Resilient',           desc: 'Choose an ability score: +1 to that score, and gain proficiency in saving throws using it.' },
  { name: 'Ritual Caster',       desc: 'Learn 2 ritual spells from a chosen class and record them in a ritual book. Can add ritual spells found as scrolls. Cast only as rituals.' },
  { name: 'Savage Attacker',     desc: 'Once per turn when making a melee weapon attack, roll the damage dice twice and use the higher result.' },
  { name: 'Sentinel',            desc: 'Opportunity attacks reduce the target\'s speed to 0. Creatures that Disengage still provoke opportunity attacks from you. Reaction attack when a creature attacks an ally within 5 ft.' },
  { name: 'Sharpshooter',        desc: 'Ignore partial cover and three-quarters cover with ranged attacks. No disadvantage at long range. −5 to attack roll for +10 damage.' },
  { name: 'Shield Master',       desc: 'Bonus action shove after Attack action. Add shield\'s AC bonus to DEX saves vs. effects targeting only you. No damage on a successful DEX save (half on fail) against area effects with DEX saves.' },
  { name: 'Skilled',             desc: 'Gain proficiency in any combination of 3 skills or tools.' },
  { name: 'Skulker',             desc: 'Hide when only lightly obscured. Missing with a ranged attack doesn\'t reveal your position. Dim light doesn\'t impose disadvantage on Perception checks relying on sight.' },
  { name: 'Spell Sniper',        desc: 'Double the range of spell attack roll spells. Ignore partial and three-quarters cover. Learn 1 cantrip with an attack roll from any class.' },
  { name: 'Tavern Brawler',      desc: '+1 STR or CON. Proficiency with improvised weapons and unarmed strikes. Unarmed strikes and improvised weapons deal 1d4. Bonus action grapple after hitting with them.' },
  { name: 'Tough',               desc: 'HP maximum increases by 2 per level (current and future levels).' },
  { name: 'War Caster',          desc: 'Advantage on CON saves to maintain concentration. Perform somatic components with hands full. Cast a spell as an opportunity attack reaction.' },
  { name: 'Weapon Master',       desc: '+1 STR or DEX. Gain proficiency with 4 weapons of your choice.' },
];

/* ============================================================
   CONDITIONS — SRD 5.1
   ============================================================ */
const SRD_CONDITIONS = [
  {
    name: 'Blinded',
    desc: "Can't see; auto-fails ability checks requiring sight. Attack rolls against have advantage; attack rolls by have disadvantage.",
  },
  {
    name: 'Charmed',
    desc: "Can't attack the charmer or target them with harmful abilities/magic. Charmer has advantage on social ability checks against the creature.",
  },
  {
    name: 'Deafened',
    desc: "Can't hear; auto-fails ability checks requiring hearing.",
  },
  {
    name: 'Exhaustion',
    desc: "Cumulative effects by level — 1: Disadvantage on ability checks. 2: Speed halved. 3: Disadvantage on attack rolls and saving throws. 4: Hit point maximum halved. 5: Speed reduced to 0. 6: Death.",
  },
  {
    name: 'Frightened',
    desc: "Disadvantage on ability checks and attack rolls while source of fear is in sight. Can't willingly move closer to the source.",
  },
  {
    name: 'Grappled',
    desc: "Speed becomes 0, can't benefit from speed bonuses. Ends if grappler is incapacitated or the creature is moved out of grapple range.",
  },
  {
    name: 'Incapacitated',
    desc: "Can't take actions or reactions.",
  },
  {
    name: 'Invisible',
    desc: "Can't be seen without magic or special senses. Counts as heavily obscured. Attacks against have disadvantage; attacks by have advantage.",
  },
  {
    name: 'Paralyzed',
    desc: "Incapacitated; can't move or speak. Auto-fails STR and DEX saves. Attack rolls against have advantage. Melee attacks within 5 ft. are critical hits.",
  },
  {
    name: 'Petrified',
    desc: "Transformed into solid matter. Incapacitated, can't move or speak, unaware of surroundings. Auto-fails STR/DEX saves. Attack rolls against have advantage. Resistance to all damage. Immune to poison and disease.",
  },
  {
    name: 'Poisoned',
    desc: "Disadvantage on attack rolls and ability checks.",
  },
  {
    name: 'Prone',
    desc: "Only movement option is crawling (costs extra). Melee attacks against have advantage; ranged attacks have disadvantage. Standing up costs half your speed.",
  },
  {
    name: 'Restrained',
    desc: "Speed becomes 0. Attack rolls against have advantage; attack rolls by have disadvantage. DEX saving throws have disadvantage.",
  },
  {
    name: 'Stunned',
    desc: "Incapacitated; can't move; can only speak falteringly. Auto-fails STR and DEX saves. Attack rolls against have advantage.",
  },
  {
    name: 'Unconscious',
    desc: "Incapacitated; can't move or speak; unaware of surroundings. Drops held items; falls prone. Auto-fails STR/DEX saves. Attacks against have advantage. Melee attacks within 5 ft. are critical hits.",
  },
];

/* ============================================================
   COMBAT ACTIONS — SRD 5.1
   ============================================================ */
const SRD_ACTIONS = [
  { name: 'Attack',          type: 'Action',       desc: "Make one or more attack rolls (weapon, unarmed, or special). Extra Attack class feature grants additional attacks." },
  { name: 'Cast a Spell',    type: 'Action / Varies', desc: "Cast a spell whose casting time is 1 action. Some spells use a bonus action or reaction instead." },
  { name: 'Dash',            type: 'Action',       desc: "Gain extra movement equal to your speed for this turn (after any modifiers)." },
  { name: 'Disengage',       type: 'Action',       desc: "Your movement doesn't provoke opportunity attacks for the rest of this turn." },
  { name: 'Dodge',           type: 'Action',       desc: "Until your next turn, attack rolls against you have disadvantage (if you can see the attacker) and you have advantage on DEX saves. Effect ends if incapacitated or speed drops to 0." },
  { name: 'Help',            type: 'Action',       desc: "Grant an ally advantage on the next ability check to accomplish a task, or give them advantage on the next attack roll against a creature within 5 ft. of you." },
  { name: 'Hide',            type: 'Action',       desc: "Make a DEX (Stealth) check. If you succeed, you are hidden until you move, attack, cast a spell, or are otherwise detected." },
  { name: 'Ready',           type: 'Action',       desc: "Choose a trigger and a response (an action or move). When the trigger occurs you may use your reaction to execute your response." },
  { name: 'Search',          type: 'Action',       desc: "Devote your attention to finding something: make a WIS (Perception) or INT (Investigation) check." },
  { name: 'Use an Object',   type: 'Action',       desc: "Interact with a second object or use an object that requires an action (e.g., administer a potion to an ally, use a magic item)." },
  { name: 'Grapple',         type: 'Special Attack', desc: "Make an Athletics check contested by the target's Athletics or Acrobatics. On success, target is Grappled. You must have a free hand." },
  { name: 'Shove',           type: 'Special Attack', desc: "Make an Athletics check contested by the target's Athletics or Acrobatics. On success, push target 5 ft. away or knock prone." },
  { name: 'Opportunity Attack', type: 'Reaction',  desc: "When a hostile creature you can see moves out of your reach, use your reaction to make one melee attack against it." },
  { name: 'Two-Weapon Fighting', type: 'Bonus Action', desc: "After attacking with a light melee weapon you hold, use your bonus action to attack with a different light melee weapon in your other hand (no ability modifier to damage unless negative)." },
  { name: 'Improvise',       type: 'Action',       desc: "Do something not covered by other actions. The DM decides if it's possible and what ability check or roll might be needed." },
];
